### ISSUE TITLE
nm_join: repair names when coercing to tibble

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbr#456]
# Summary
As a user, I want `nm_join()` to repair duplicate names when coercing to `tibble()`.

**Comment by kylebaron** [comment]
The issue probably originates with `nm_file()`

**Comment by barrettk** [comment]
I've started looking into this. Might need some clarification because I think the issue is not related to `nm_file`/`nm_tables`. My understanding is that we want a new argument that controls dropping of duplicated variables (seems like we dont want to necessarily get rid of that functionality). In cases where multiple table files reference the same variable (ex: CL, KA),  we want the _option_ to keep both. Think this could be done with something like:
```r
> make.unique(c("A", "B", "A", "B", "A"), sep="_")
[1] "A"   "B"   "A_1" "B_1" "A_2"
```
 but with more information, such as `A.tab`, `A.par_tab`, etc., which gets done after reading in the tables. 

For the moment, Ill append a requirement to `nm_join`, rather than `nm_tables`/`nm_file`

OUT-S003:
  name: Join NONMEM tables to input data
  description: As a user, I want to be able to pass a model object and have bbr extract
    the input data path and path to any table outputs from the control stream and
    join the contents of those files together into a single tibble.
  ProductRisk: Low
  requirements: 
     - NMJ-R001 (previous requirement)
     - NMJ-R002 (exists, but not added to story - I think it should be)
     - NMJ-R004 (exists, but not added to story - I think it should be)
     - NMJ-R007 (new)
     
     
_New_ Requirements:
```
NMJ-R007:
  description: nm_join() can optionally repair duplicate names when coercing to tibble(). Duplicate variables are appended by the referenced table file.
  tests: 
```

In the above description, an example can be seen with how `DV` is handled, which becomes `DV.Data`

**Comment by seth127** [comment]
@kylebaron I want to clarify this a bit. The current behavior of `nm_join()` (documented [here](https://github.com/metrumresearchgroup/bbr/blob/develop/R/nm-join.R#L53-L63)) is do drop duplicated columns, except for `DV` which has special handling. Do you want to _change_ that behavior? 

If so, would you like an argument to _optionally_ change that behavior (as @barrettk proposes above), or are you proposing this should be the new behavior?

**Comment by kylebaron** [comment]
@seth127 When people table out the same data item twice, you will have duplicate names. This causes an error when you coerce the data table / data frame to tibble. I think you need to specify an value for `.names_repair` to make it work.

**Comment by seth127** [comment]
Sorry, I was confused in earlier comment. This issue is about when an _individual table file_ has duplicate column names, not when the join creates duplicate column names. My mistake. @kylebaron was correct earlier to point us towards `nm_file()` as the having the problem.

Proposed fix is to add a warning and repair the names before converting to tibble inside `nm_file()`. Something like the following (pseudo-code):

```r
colnames <- names(data)
dups <- duplicated(colnames)
if (any(dups)) {
  warn(glue("The following column names are duplicated in {filename}: {paste(colnames[dups])}\n  Duplicate names will be repaired with `make.unique()`"))
  names(data) <- make.unique(colnames)
}
```

# Semi-related NONMEM issue

In investigating this, we came upon a NONMEM control stream that wrote out a table with duplicated column names, even though the `$TAB` did _not_ ask for those columns twice. This is strange and still unexplained. However, at this point we're _not_ looking into that, because we would handle it the same way (in `nm_file()`) regardless of whether the control stream specifies writing out the duplicate column or not. I just wanted to note this here, in case this issue comes up further down the line.

**Comment by seth127** [comment]
Also, ignore requirements related to `nm_join()` above (by @barrettk). Instead this fix should add a requirement like 

```
NMF-R008:
  description: nm_file() repairs duplicate column names that are present in input file
  tests: ...
```
