### ISSUE TITLE
Option to start bootstrap runs at final estimates from parent run

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbr#690]
# Summary 

- Initially, clobber initial estimates in  `$THETA`, `$OMEGA`, `$SIGMA` and use `$MSFI` instead
- Opt in

**Comment by seth127** [comment]
Thanks Kyle. This isn't exactly what you're describing, but I think this is essentially possible via the new [`inherit_param_estimates()`](https://metrumresearchgroup.github.io/bbr/reference/inherit_param_estimates.html) function. Something like

```r
boot_run <- parent mod %>%
    new_bootstrap_run() %>%
    inherit_param_estimates()
```

_Note:_ As of the most recent [`1.10.0.8003`](https://github.com/metrumresearchgroup/bbr/releases/tag/1.10.0.8003) dev tag, this doesn't work because we haven't added the necessary S3 dispatches. The plan is to fix that before release though. Some discussion of this exact issue is in [this comment on #679](https://github.com/metrumresearchgroup/bbr/issues/679#issuecomment-2103107911).

**Comment by seth127** [comment]
Yes, we can close this. Users who want to do this can use the pattern in my comment above.
